#!/bin/bash

if ! type kubectl &>/dev/null; then
    echo "kubectl command not found" >&2
    exit 1
fi

if ! context="$(kubectl config current-context 2>/dev/null)"; then
    echo "NaN"
    exit 0
fi

namespace="$(kubectl config view -o "jsonpath={.contexts[?(@.name==\"$context\")].context.namespace}")"
if [[ -z "$namespace" ]]; then
    namespace="default"
fi

regions=(
"us-west1-a" "us-west1-b"
"us-central1-a" "us-central1-b" "us-central1-c" "us-central1-f"
"us-east1-b" "us-east1-c" "us-east1-d"
"europe-west1-b" "europe-west1-c" "europe-west1-d"
"asia-southeast1-a" "asia-southeast1-b"
"asia-east1-a" "asia-east1-b" "asia-east1-c"
"asia-northeast1-a" "asia-northeast1-b" "asia-northeast1-c"
)

for region in "${regions[@]}"
do
    context=${context%_${region}*}
done

echo "${context}/${namespace}"
